### ISSUE TITLE
ASN.1

### ISSUE THREAD

**Issue by Spomky** [mdanter/phpecc#52]
Hi,

You use FGrosse/PHPASN1 library as a dependency, but this dependency is not stable.
Is it possible to remove this dependency and use [PHPSecLib](https://github.com/phpseclib/phpseclib) instead ?

You can look at [this library](https://github.com/namshi/jose/blob/master/src/Namshi/JOSE/Signer/ECDSA.php) to know how they use it to read a file.

**Comment by btcdrak** [comment]
It certain looks well maintained.

**Comment by aztech-dev** [comment]
I did not use PHPSecLib because it means importing a full sec package just to get ASN encoding/decoding, which is bloat IMO. I'd definitely rather use an ASN-only library, if you know any that fits your criteria of stable without having to import a load of unrelated classes, please do suggest it :)

Regarding stability, current composer file is locked at a specific commit, and since the owner did merge my P/R for a composer file, I'm pretty sure he'd be willing to tag a release to solve that "unstable" problem.

Plus, I dislike very much anything that is using arrays instead of proper object graphs :smiling_imp:

**Comment by btcdrak** [comment]
@aztech-dev I dont agree with a decision based on "bloat". The whole point of package managers like composer is it simple doesn't matter. If the library is better maintained, we should use it.

**Comment by aztech-dev** [comment]
@btcdrak For "projects" I totally agree. 

For "libraries", I think it is a responsibility of the maintainer to keep it as small/focused as possible. And that includes not introducing any unnecessary code. Going by your philosophy, I could just include the whole Symfony framework (disregarding the fact that it is componentized) just because I need one class, and because **I can with Composer**. And oh wait, I need one class from Laravel... Just like it's not because you can use arrays for nothing and everything in PHP that you should...

As for maintenance, well, current dependency is maintained, sure not as often as phpseclib, but the owner does react and respond to issues. I don't find it shocking neither a sign of bad maintenance that the library is not updated monthly, considering ASN.1 is well over 20 years old.

Aside from that, if anyone P/R's the change, so be it, but I certainly won't go and rewrite functional code, that so far is compatible with OpenSSL just because it does not have a version tag (which can be added in less time that it takes to rewrite the de/serialization classes). 

**Might be anal**, but I did invest quite some time in this feature, so I obviously find it vexing to ask to rewrite it for a simple tagging issue (disregarding again the fact that I consider array based data structures to be an aberration of PHP promoting improper coder laziness and requiring you to manually do things provided for free by real object graphs -- you do OO, or you don't).

**Comment by Spomky** [comment]
@aztech-dev OK I understand your point of view.
That is right that most of classes provided by PHPSecLib are useless for this library.

I also have the same problem with composer as reported in #53.
So, rather than having another dependency, I will create a PR to improve [FGrosse/PHPASN1](https://github.com/FGrosse/PHPASN1) regarding the autoloading especially.

**Comment by Spomky** [comment]
[PR submitted](https://github.com/FGrosse/PHPASN1/pull/27). Feel free to comment it.

**Comment by aztech-dev** [comment]
Great, thanks a bunch @FGrosse :)

**Comment by aztech-dev** [comment]
And great job @Spomky that was a fast and efficient refactor :)

**Comment by FGrosse** [comment]
@Spomky thats for sure. Also saved me a lot of time
