### ISSUE TITLE
readme wrong

### ISSUE THREAD

**Issue by FabioCarpi** [mdanter/phpecc#62]
the command $alice = $generator->createPrivateKey(); dont work

**Comment by aztech-dev** [comment]
Can you give more information about the error (version of phpecc used ? stable release ? what's the error output) ?

As far as I am concerned, https://github.com/mdanter/phpecc/blob/master/tests/unit/EcDhMultiPartyTest.php#L14 is a passing test, and it uses exactly the same statement.

**Comment by aztech-dev** [comment]
Test https://github.com/mdanter/phpecc/blob/master/tests/unit/Curves/NistCurveTest.php#L299 also covers the exact scenario described in README.md

**Comment by FabioCarpi** [comment]
im using the curve secp256k1

**Comment by aztech-dev** [comment]
And what is the error you are having exactly ? What is the output ? "dont work" is not very helpful...

Also are you using v0.0.2, the lastest from master, or another specific commit ?

**Comment by FabioCarpi** [comment]
i recreate my scenario here, but the problem its gone...
sorry for any trouble

**Comment by aztech-dev** [comment]
No problem... glad it fixed itself :)

**Comment by FabioCarpi** [comment]
can u helmp with one thing? i get na object privkey with this. how i can get a privkey like bitcoin system?

**Comment by aztech-dev** [comment]
That's outside of the scope of this project. You should try to use a library like https://github.com/Bit-Wasp/bitcoin-lib-php which is more bitcoin specific.

**Comment by aztech-dev** [comment]
(but basically, you need to call $privateKey->getSecret(), and the value returned is your private key).

**Comment by FabioCarpi** [comment]
i know that and im using this Project. but this project its not following the updates of the eccphp. and with the last update, creating the public key its taking a long time, timeouting... for that im looking for new forms the generate keys

**Comment by aztech-dev** [comment]
Well once you have a private object, you can also do `$publicKey = $privateKey->getPublicKey()`. You can then call `$publicKey->getPoint()` to get the X/Y coordinates of the public key, and you have all the information needed to derive Bitcoin addresses from there (see https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses for how to do it). It's pretty much a matter of applying a series of hashing function to the public key coordinates.

**Comment by FabioCarpi** [comment]
thanks a lot.
abusing a little ;) how i create the object privkey getting a bitcoin privkey?

**Comment by aztech-dev** [comment]
Not sure what you mean. Unless I am mistaken, once you generate a private key using secp256k1, the private key object you get is a Bitcoin private key. You just need to hex encode the output of '$privateKey->getSecret()`.

**Comment by FabioCarpi** [comment]
It's not that. Creating the object from a private stored in database. From a secret...

**Comment by afk11** [comment]
Hey @FabioCarpi! I'll have a look today, I chose a specific commit for that library because phpecc has had a number of BC breaking changes to date, and it's nice to still have working code after leaving it for a few months :) 

If you want I can add you on hangouts and try give you a a rundown on how the libs work together? Fire me an email here me@thomaskerin.io

"how i can get a privkey like bitcoin system?" It'll be clearer as you go on but Bitcoin doesn't make use of private keys in their hex or WIF form. In elliptic curve crypto, private keys are decimal integers. 

So when you have a PHPECC object for a PublicKey, or PrivateKey, you are interested in the (x,y) decimal coordinates, or k, the decimal private key as thats how operations are carried out. How you encode later is up to you :)

"creating the public key its taking a long time," Maybe raise a separate issue to discuss, but for your sanity make sure you have GMP installed.

**Comment by aztech-dev** [comment]
It's quite simple then:

```
$secret = '...Your database value...';
$generator = EccFactory::getSecpFactory()->generator256k1();
$privateKey = $generator->getPrivateKeyFrom($secret);
```

**Comment by aztech-dev** [comment]
But regardless, you should prefer working with bitcoinlib-php (and report issues as @afk11 mentionned) rather than trying to maintain your own implementation

**Comment by FabioCarpi** [comment]
Thank you all guys for the patience...

**Comment by afk11** [comment]
No probs! I'll be bumping bitcoin-lib-php to use the latest phpecc soon (see the issue about BC breaks). 
I see you're writing this bitcoin stuff for study anyways, feel free ping me on the email above or steal code from bitcoinlib or https://github.com/afk11/bitcoin
