### ISSUE TITLE
Bug: EcDH calls nonexistent method PrivateKey::getX()

### ISSUE THREAD

**Issue by afk11** [mdanter/phpecc#77]
https://github.com/mdanter/phpecc/blob/master/src/EcDH.php#L122

**Comment by aztech-dev** [comment]
Actually, it calls PointInterface::getX(), however, you need to calculate the shared key first via EcDH::calculateSharedKey() first. https://github.com/mdanter/phpecc/blob/master/tests/unit/EcDhMultiPartyTest.php would fail otherwise.

It's true however that a little null check with an exception when the shared key is not calculated would not hurt anyone...

**Comment by aztech-dev** [comment]
This test would also fail

https://github.com/mdanter/phpecc/blob/master/tests/unit/Curves/NistCurveTest.php#L297

**Comment by afk11** [comment]
Ah I see. in my haste I didn't mention this is taken from the readme. Maybe either PrivateKey::createExchange could call calculateSharedKey, but for now I just added it to the readme!

I also tweaked checkExchangeState to fail if sharedKey === null, will see how tests do and submit.

**Comment by aztech-dev** [comment]
Hum... if you throw an exception in checkExchangeState when secretKey is null, your tests will fail, as checkExchangeState is called prior to calculate the shared secret key. 

Instead, you probably should add another validation method, as checkExchangeState is meant to verify that the shared secret key can be calculated.

**Comment by aztech-dev** [comment]
Implicitely calling calculateSharedKey is actually fine by me, as it would throw an exception when trying to encrypt/decrypt without having the keys set.

**Comment by afk11** [comment]
Cool, I went with that! https://github.com/mdanter/phpecc/pull/78

**Comment by afk11** [comment]
Closing this issue, PR ready to be merged.
